import { SavedDataStructure } from "@/types/SavedDataTypes";

export const demoData = [
  {
    ID: 1,
    Category: "Sports",
    Subcategory: "Apparel",
    Size: "Small",
    Color: "Green",
    Material: "Metal",
    Brand: "Epsilon",
    "Price Range": "Mid-range",
    Rating: 4,
    "In Stock": true,
    "Shipping Weight": 18.95,
    "Age Group": "Seniors",
  },
  {
    ID: 2,
    Category: "Sports",
    Subcategory: "Apparel",
    Size: "Large",
    Color: "Blue",
    Material: "Wood",
    Brand: "Gamma",
    "Price Range": "Premium",
    Rating: 2,
    "In Stock": true,
    "Shipping Weight": 14.58,
    "Age Group": "Seniors",
  },
  {
    ID: 3,
    Category: "Electronics",
    Subcategory: "Laptops",
    Size: "Small",
    Color: "Blue",
    Material: "Wood",
    Brand: "Gamma",
    "Price Range": "Budget",
    Rating: 4,
    "In Stock": true,
    "Shipping Weight": 15.12,
    "Age Group": "Adults",
  },
  {
    ID: 4,
    Category: "Home",
    Subcategory: "Kitchen",
    Size: "Small",
    Color: "White",
    Material: "Cotton",
    Brand: "Alpha",
    "Price Range": "Luxury",
    Rating: 4,
    "In Stock": true,
    "Shipping Weight": 6.01,
    "Age Group": "Seniors",
  },
  {
    ID: 5,
    Category: "Home",
    Subcategory: "Kitchen",
    Size: "Large",
    Color: "Blue",
    Material: "Leather",
    Brand: "Delta",
    "Price Range": "Luxury",
    Rating: 4,
    "In Stock": false,
    "Shipping Weight": 5.45,
    "Age Group": "Teens",
  },
  {
    ID: 6,
    Category: "Electronics",
    Subcategory: "Phones",
    Size: "Medium",
    Color: "White",
    Material: "Plastic",
    Brand: "Delta",
    "Price Range": "Luxury",
    Rating: 1,
    "In Stock": true,
    "Shipping Weight": 10.13,
    "Age Group": "Seniors",
  },
  {
    ID: 7,
    Category: "Clothing",
    Subcategory: "Pants",
    Size: "Large",
    Color: "Purple",
    Material: "Plastic",
    Brand: "Alpha",
    "Price Range": "Premium",
    Rating: 1,
    "In Stock": true,
    "Shipping Weight": 3.63,
    "Age Group": "Adults",
  },
  {
    ID: 8,
    Category: "Clothing",
    Subcategory: "Shoes",
    Size: "Small",
    Color: "Purple",
    Material: "Glass",
    Brand: "Alpha",
    "Price Range": "Mid-range",
    Rating: 2,
    "In Stock": true,
    "Shipping Weight": 9.74,
    "Age Group": "Seniors",
  },
  {
    ID: 9,
    Category: "Home",
    Subcategory: "Bath",
    Size: "Large",
    Color: "Red",
    Material: "Cotton",
    Brand: "Gamma",
    "Price Range": "Premium",
    Rating: 5,
    "In Stock": true,
    "Shipping Weight": 11.1,
    "Age Group": "Seniors",
  },
  {
    ID: 10,
    Category: "Food",
    Subcategory: "Snacks",
    Size: "Large",
    Color: "Purple",
    Material: "Metal",
    Brand: "Gamma",
    "Price Range": "Luxury",
    Rating: 4,
    "In Stock": true,
    "Shipping Weight": 10.04,
    "Age Group": "Teens",
  },
  {
    ID: 11,
    Category: "Electronics",
    Subcategory: "Laptops",
    Size: "Medium",
    Color: "Purple",
    Material: "Plastic",
    Brand: "Delta",
    "Price Range": "Luxury",
    Rating: 1,
    "In Stock": true,
    "Shipping Weight": 1.68,
    "Age Group": "Adults",
  },
  {
    ID: 12,
    Category: "Clothing",
    Subcategory: "Dresses",
    Size: "Large",
    Color: "Black",
    Material: "Wood",
    Brand: "Epsilon",
    "Price Range": "Budget",
    Rating: 2,
    "In Stock": true,
    "Shipping Weight": 6.24,
    "Age Group": "Teens",
  },
  {
    ID: 13,
    Category: "Sports",
    Subcategory: "Nutrition",
    Size: "Medium",
    Color: "Blue",
    Material: "Metal",
    Brand: "Beta",
    "Price Range": "Mid-range",
    Rating: 2,
    "In Stock": false,
    "Shipping Weight": 0.27,
    "Age Group": "Children",
  },
  {
    ID: 14,
    Category: "Clothing",
    Subcategory: "Shirts",
    Size: "Large",
    Color: "Yellow",
    Material: "Metal",
    Brand: "Beta",
    "Price Range": "Budget",
    Rating: 4,
    "In Stock": false,
    "Shipping Weight": 12.55,
    "Age Group": "Adults",
  },
  {
    ID: 15,
    Category: "Sports",
    Subcategory: "Equipment",
    Size: "Large",
    Color: "White",
    Material: "Cotton",
    Brand: "Beta",
    "Price Range": "Budget",
    Rating: 2,
    "In Stock": false,
    "Shipping Weight": 11.57,
    "Age Group": "Adults",
  },
  {
    ID: 16,
    Category: "Home",
    Subcategory: "Bath",
    Size: "Small",
    Color: "Red",
    Material: "Plastic",
    Brand: "Alpha",
    "Price Range": "Budget",
    Rating: 3,
    "In Stock": false,
    "Shipping Weight": 1.5,
    "Age Group": "Teens",
  },
  {
    ID: 17,
    Category: "Clothing",
    Subcategory: "Shoes",
    Size: "Small",
    Color: "Purple",
    Material: "Plastic",
    Brand: "Epsilon",
    "Price Range": "Premium",
    Rating: 3,
    "In Stock": true,
    "Shipping Weight": 0.56,
    "Age Group": "Children",
  },
  {
    ID: 18,
    Category: "Sports",
    Subcategory: "Equipment",
    Size: "Small",
    Color: "Red",
    Material: "Wood",
    Brand: "Alpha",
    "Price Range": "Mid-range",
    Rating: 4,
    "In Stock": true,
    "Shipping Weight": 18.22,
    "Age Group": "Seniors",
  },
  {
    ID: 19,
    Category: "Electronics",
    Subcategory: "Phones",
    Size: "Small",
    Color: "Yellow",
    Material: "Leather",
    Brand: "Gamma",
    "Price Range": "Mid-range",
    Rating: 1,
    "In Stock": false,
    "Shipping Weight": 0.71,
    "Age Group": "Adults",
  },
  {
    ID: 20,
    Category: "Home",
    Subcategory: "Kitchen",
    Size: "Medium",
    Color: "Black",
    Material: "Cotton",
    Brand: "Epsilon",
    "Price Range": "Mid-range",
    Rating: 1,
    "In Stock": false,
    "Shipping Weight": 14.95,
    "Age Group": "Seniors",
  },
  {
    ID: 21,
    Category: "Electronics",
    Subcategory: "Accessories",
    Size: "Medium",
    Color: "Green",
    Material: "Leather",
    Brand: "Epsilon",
    "Price Range": "Mid-range",
    Rating: 4,
    "In Stock": true,
    "Shipping Weight": 5.66,
    "Age Group": "Teens",
  },
  {
    ID: 22,
    Category: "Food",
    Subcategory: "Snacks",
    Size: "Large",
    Color: "Red",
    Material: "Leather",
    Brand: "Epsilon",
    "Price Range": "Budget",
    Rating: 2,
    "In Stock": true,
    "Shipping Weight": 15.03,
    "Age Group": "Seniors",
  },
  {
    ID: 23,
    Category: "Food",
    Subcategory: "Frozen",
    Size: "Small",
    Color: "Blue",
    Material: "Glass",
    Brand: "Delta",
    "Price Range": "Mid-range",
    Rating: 4,
    "In Stock": false,
    "Shipping Weight": 12.62,
    "Age Group": "Seniors",
  },
  {
    ID: 24,
    Category: "Food",
    Subcategory: "Snacks",
    Size: "Medium",
    Color: "White",
    Material: "Glass",
    Brand: "Beta",
    "Price Range": "Mid-range",
    Rating: 4,
    "In Stock": false,
    "Shipping Weight": 18.54,
    "Age Group": "Children",
  },
  {
    ID: 25,
    Category: "Clothing",
    Subcategory: "Shirts",
    Size: "Small",
    Color: "Green",
    Material: "Wood",
    Brand: "Epsilon",
    "Price Range": "Mid-range",
    Rating: 5,
    "In Stock": true,
    "Shipping Weight": 17.02,
    "Age Group": "Adults",
  },
  {
    ID: 26,
    Category: "Clothing",
    Subcategory: "Dresses",
    Size: "Large",
    Color: "Purple",
    Material: "Glass",
    Brand: "Beta",
    "Price Range": "Luxury",
    Rating: 1,
    "In Stock": false,
    "Shipping Weight": 17.45,
    "Age Group": "Adults",
  },
  {
    ID: 27,
    Category: "Sports",
    Subcategory: "Nutrition",
    Size: "Small",
    Color: "Yellow",
    Material: "Wood",
    Brand: "Gamma",
    "Price Range": "Budget",
    Rating: 3,
    "In Stock": false,
    "Shipping Weight": 14.61,
    "Age Group": "Seniors",
  },
  {
    ID: 28,
    Category: "Clothing",
    Subcategory: "Dresses",
    Size: "Medium",
    Color: "Purple",
    Material: "Leather",
    Brand: "Beta",
    "Price Range": "Budget",
    Rating: 4,
    "In Stock": true,
    "Shipping Weight": 14.07,
    "Age Group": "Seniors",
  },
  {
    ID: 29,
    Category: "Food",
    Subcategory: "Fresh",
    Size: "Small",
    Color: "Green",
    Material: "Leather",
    Brand: "Delta",
    "Price Range": "Luxury",
    Rating: 5,
    "In Stock": true,
    "Shipping Weight": 17.71,
    "Age Group": "Children",
  },
  {
    ID: 30,
    Category: "Home",
    Subcategory: "Bath",
    Size: "Small",
    Color: "Black",
    Material: "Cotton",
    Brand: "Beta",
    "Price Range": "Premium",
    Rating: 1,
    "In Stock": true,
    "Shipping Weight": 5.96,
    "Age Group": "Seniors",
  },
];

export const demoSettings: SavedDataStructure = {
  charts: [
    {
      id: "cffc1655-4e70-4564-aec0-91aaa6b247d5",
      type: "row",
      title: "Row Chart - Category",
      field: "Category",
      layout: { x: 0, y: 0, w: 7, h: 4 },
      colorScaleId: "a7c2c25b-f6c5-4040-8b2c-6db7326e6c05",
      minRowHeight: 10,
      maxRowHeight: 100,
      filterValues: { values: [] },
      facet: {
        enabled: true,
        type: "wrap",
        rowVariable: "Size",
        columnCount: 2,
      },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      colorField: "Category",
    },
    {
      id: "9f11ed89-bd1a-436b-949f-b0f213a95c14",
      type: "row",
      title: "Row Chart - Category",
      field: "Category",
      layout: { x: 8, y: 0, w: 4, h: 4 },
      minRowHeight: 10,
      maxRowHeight: 100,
      filterValues: { values: [] },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
    },
    {
      type: "row",
      title: "Row Chart - Category",
      field: "Category",
      layout: { x: 0, y: 18, w: 12, h: 4 },
      minRowHeight: 10,
      maxRowHeight: 100,
      filterValues: { values: [] },
      facet: {
        enabled: true,
        type: "grid",
        rowVariable: "Size",
        columnCount: 2,
        columnVariable: "In Stock",
      },
      id: "a1d00ac6-5255-476b-a0a9-93ed78bd152e",
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
    },
    {
      id: "0f14fcfa-f7ed-477c-9ed1-f01ad217b2c4",
      type: "scatter",
      title: "Scatter Plot - ID vs __ID",
      field: "ID",
      xField: "ID",
      yField: "Rating",
      layout: { x: 0, y: 8, w: 12, h: 7 },
      xFilterRange: null,
      yFilterRange: null,
      facet: {
        enabled: true,
        type: "wrap",
        rowVariable: "Color",
        columnCount: 4,
      },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      colorField: "",
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
    },
    {
      type: "scatter",
      title: "Scatter Plot - ID vs __ID",
      field: "ID",
      xField: "ID",
      yField: "Rating",
      layout: { x: 0, y: 15, w: 8, h: 3 },
      xFilterRange: null,
      yFilterRange: null,
      facet: {
        enabled: false,
        type: "wrap",
        rowVariable: "Color",
        columnCount: 4,
      },
      id: "0ef4c4ee-6a4d-48ec-9641-402f94b11e6b",
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      colorField: "",
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
    },
    {
      id: "c2328c28-8c82-41bc-9174-92525abf77f8",
      type: "bar",
      title: "Bar Chart - Rating",
      field: "Rating",
      layout: { x: 5, y: 4, w: 7, h: 4 },
      filterValues: { values: [] },
      filterRange: null,
      facet: {
        enabled: true,
        type: "wrap",
        rowVariable: "In Stock",
        columnCount: 2,
      },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      binCount: 10,
      forceString: false,
    },
    {
      id: "e2b6237d-a558-4faf-8430-774d91744e9f",
      type: "bar",
      title: "Bar Chart - Rating",
      field: "Rating",
      layout: { x: 0, y: 4, w: 5, h: 4 },
      filterValues: { values: [] },
      filterRange: null,
    },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: true,
  },
  metadata: {
    name: "Untitled",
    version: 1,
    createdAt: "2025-03-04T21:21:10.905Z",
    modifiedAt: "2025-03-04T21:21:10.905Z",
  },
  colorScales: [
    {
      name: "Category",
      type: "categorical",
      palette: ["#8dd3c7", "#ffffb3", "#bebada", "#fb8072", "#80b1d3"],
      mapping: [
        ["Sports", "#8dd3c7"],
        ["Electronics", "#ffffb3"],
        ["Home", "#bebada"],
        ["Clothing", "#fb8072"],
        ["Food", "#80b1d3"],
      ],
      id: "a7c2c25b-f6c5-4040-8b2c-6db7326e6c05",
    },
    {
      name: "Color",
      type: "categorical",
      palette: [
        "#1f77b4",
        "#ff7f0e",
        "#2ca02c",
        "#d62728",
        "#9467bd",
        "#8c564b",
        "#e377c2",
      ],
      mapping: [
        ["Green", "#1f77b4"],
        ["Blue", "#ff7f0e"],
        ["White", "#2ca02c"],
        ["Purple", "#d62728"],
        ["Red", "#9467bd"],
        ["Black", "#8c564b"],
        ["Yellow", "#e377c2"],
      ],
      id: "5f712155-15ea-4288-a0c9-e560429da9c7",
    },
    {
      name: "Rating",
      type: "numerical",
      palette: "Viridis",
      min: 1,
      max: 5,
      id: "0d3c39e5-5fc4-4eee-a365-1de32c0c95b2",
    },
  ],
};
