import crossfilter from "crossfilter2";
import { cloneDeep } from "./cloneDeep";

export const demoData = [
  {
    ID: 1,
    Category: "Sports",
    Subcategory: "Apparel",
    Size: "Small",
    Color: "Green",
    Material: "Metal",
    Brand: "Epsilon",
    "Price Range": "Mid-range",
    Rating: 4,
    "In Stock": true,
    "Shipping Weight": 18.95,
    "Age Group": "Seniors",
  },
  {
    ID: 2,
    Category: "Sports",
    Subcategory: "Apparel",
    Size: "Large",
    Color: "Blue",
    Material: "Wood",
    Brand: "Gamma",
    "Price Range": "Premium",
    Rating: 2,
    "In Stock": true,
    "Shipping Weight": 14.58,
    "Age Group": "Seniors",
  },
  {
    ID: 3,
    Category: "Electronics",
    Subcategory: "Laptops",
    Size: "Small",
    Color: "Blue",
    Material: "Wood",
    Brand: "Gamma",
    "Price Range": "Budget",
    Rating: 4,
    "In Stock": true,
    "Shipping Weight": 15.12,
    "Age Group": "Adults",
  },
  {
    ID: 4,
    Category: "Home",
    Subcategory: "Kitchen",
    Size: "Small",
    Color: "White",
    Material: "Cotton",
    Brand: "Alpha",
    "Price Range": "Luxury",
    Rating: 4,
    "In Stock": true,
    "Shipping Weight": 6.01,
    "Age Group": "Seniors",
  },
  {
    ID: 5,
    Category: "Home",
    Subcategory: "Kitchen",
    Size: "Large",
    Color: "Blue",
    Material: "Leather",
    Brand: "Delta",
    "Price Range": "Luxury",
    Rating: 4,
    "In Stock": false,
    "Shipping Weight": 5.45,
    "Age Group": "Teens",
  },
  {
    ID: 6,
    Category: "Electronics",
    Subcategory: "Phones",
    Size: "Medium",
    Color: "White",
    Material: "Plastic",
    Brand: "Delta",
    "Price Range": "Luxury",
    Rating: 1,
    "In Stock": true,
    "Shipping Weight": 10.13,
    "Age Group": "Seniors",
  },
  {
    ID: 7,
    Category: "Clothing",
    Subcategory: "Pants",
    Size: "Large",
    Color: "Purple",
    Material: "Plastic",
    Brand: "Alpha",
    "Price Range": "Premium",
    Rating: 1,
    "In Stock": true,
    "Shipping Weight": 3.63,
    "Age Group": "Adults",
  },
  {
    ID: 8,
    Category: "Clothing",
    Subcategory: "Shoes",
    Size: "Small",
    Color: "Purple",
    Material: "Glass",
    Brand: "Alpha",
    "Price Range": "Mid-range",
    Rating: 2,
    "In Stock": true,
    "Shipping Weight": 9.74,
    "Age Group": "Seniors",
  },
  {
    ID: 9,
    Category: "Home",
    Subcategory: "Bath",
    Size: "Large",
    Color: "Red",
    Material: "Cotton",
    Brand: "Gamma",
    "Price Range": "Premium",
    Rating: 5,
    "In Stock": true,
    "Shipping Weight": 11.1,
    "Age Group": "Seniors",
  },
  {
    ID: 10,
    Category: "Food",
    Subcategory: "Snacks",
    Size: "Large",
    Color: "Purple",
    Material: "Metal",
    Brand: "Gamma",
    "Price Range": "Luxury",
    Rating: 4,
    "In Stock": true,
    "Shipping Weight": 10.04,
    "Age Group": "Teens",
  },
  {
    ID: 11,
    Category: "Electronics",
    Subcategory: "Laptops",
    Size: "Medium",
    Color: "Purple",
    Material: "Plastic",
    Brand: "Delta",
    "Price Range": "Luxury",
    Rating: 1,
    "In Stock": true,
    "Shipping Weight": 1.68,
    "Age Group": "Adults",
  },
  {
    ID: 12,
    Category: "Clothing",
    Subcategory: "Dresses",
    Size: "Large",
    Color: "Black",
    Material: "Wood",
    Brand: "Epsilon",
    "Price Range": "Budget",
    Rating: 2,
    "In Stock": true,
    "Shipping Weight": 6.24,
    "Age Group": "Teens",
  },
  {
    ID: 13,
    Category: "Sports",
    Subcategory: "Nutrition",
    Size: "Medium",
    Color: "Blue",
    Material: "Metal",
    Brand: "Beta",
    "Price Range": "Mid-range",
    Rating: 2,
    "In Stock": false,
    "Shipping Weight": 0.27,
    "Age Group": "Children",
  },
  {
    ID: 14,
    Category: "Clothing",
    Subcategory: "Shirts",
    Size: "Large",
    Color: "Yellow",
    Material: "Metal",
    Brand: "Beta",
    "Price Range": "Budget",
    Rating: 4,
    "In Stock": false,
    "Shipping Weight": 12.55,
    "Age Group": "Adults",
  },
  {
    ID: 15,
    Category: "Sports",
    Subcategory: "Equipment",
    Size: "Large",
    Color: "White",
    Material: "Cotton",
    Brand: "Beta",
    "Price Range": "Budget",
    Rating: 2,
    "In Stock": false,
    "Shipping Weight": 11.57,
    "Age Group": "Adults",
  },
  {
    ID: 16,
    Category: "Home",
    Subcategory: "Bath",
    Size: "Small",
    Color: "Red",
    Material: "Plastic",
    Brand: "Alpha",
    "Price Range": "Budget",
    Rating: 3,
    "In Stock": false,
    "Shipping Weight": 1.5,
    "Age Group": "Teens",
  },
  {
    ID: 17,
    Category: "Clothing",
    Subcategory: "Shoes",
    Size: "Small",
    Color: "Purple",
    Material: "Plastic",
    Brand: "Epsilon",
    "Price Range": "Premium",
    Rating: 3,
    "In Stock": true,
    "Shipping Weight": 0.56,
    "Age Group": "Children",
  },
  {
    ID: 18,
    Category: "Sports",
    Subcategory: "Equipment",
    Size: "Small",
    Color: "Red",
    Material: "Wood",
    Brand: "Alpha",
    "Price Range": "Mid-range",
    Rating: 4,
    "In Stock": true,
    "Shipping Weight": 18.22,
    "Age Group": "Seniors",
  },
  {
    ID: 19,
    Category: "Electronics",
    Subcategory: "Phones",
    Size: "Small",
    Color: "Yellow",
    Material: "Leather",
    Brand: "Gamma",
    "Price Range": "Mid-range",
    Rating: 1,
    "In Stock": false,
    "Shipping Weight": 0.71,
    "Age Group": "Adults",
  },
  {
    ID: 20,
    Category: "Home",
    Subcategory: "Kitchen",
    Size: "Medium",
    Color: "Black",
    Material: "Cotton",
    Brand: "Epsilon",
    "Price Range": "Mid-range",
    Rating: 1,
    "In Stock": false,
    "Shipping Weight": 14.95,
    "Age Group": "Seniors",
  },
  {
    ID: 21,
    Category: "Electronics",
    Subcategory: "Accessories",
    Size: "Medium",
    Color: "Green",
    Material: "Leather",
    Brand: "Epsilon",
    "Price Range": "Mid-range",
    Rating: 4,
    "In Stock": true,
    "Shipping Weight": 5.66,
    "Age Group": "Teens",
  },
  {
    ID: 22,
    Category: "Food",
    Subcategory: "Snacks",
    Size: "Large",
    Color: "Red",
    Material: "Leather",
    Brand: "Epsilon",
    "Price Range": "Budget",
    Rating: 2,
    "In Stock": true,
    "Shipping Weight": 15.03,
    "Age Group": "Seniors",
  },
  {
    ID: 23,
    Category: "Food",
    Subcategory: "Frozen",
    Size: "Small",
    Color: "Blue",
    Material: "Glass",
    Brand: "Delta",
    "Price Range": "Mid-range",
    Rating: 4,
    "In Stock": false,
    "Shipping Weight": 12.62,
    "Age Group": "Seniors",
  },
  {
    ID: 24,
    Category: "Food",
    Subcategory: "Snacks",
    Size: "Medium",
    Color: "White",
    Material: "Glass",
    Brand: "Beta",
    "Price Range": "Mid-range",
    Rating: 4,
    "In Stock": false,
    "Shipping Weight": 18.54,
    "Age Group": "Children",
  },
  {
    ID: 25,
    Category: "Clothing",
    Subcategory: "Shirts",
    Size: "Small",
    Color: "Green",
    Material: "Wood",
    Brand: "Epsilon",
    "Price Range": "Mid-range",
    Rating: 5,
    "In Stock": true,
    "Shipping Weight": 17.02,
    "Age Group": "Adults",
  },
  {
    ID: 26,
    Category: "Clothing",
    Subcategory: "Dresses",
    Size: "Large",
    Color: "Purple",
    Material: "Glass",
    Brand: "Beta",
    "Price Range": "Luxury",
    Rating: 1,
    "In Stock": false,
    "Shipping Weight": 17.45,
    "Age Group": "Adults",
  },
  {
    ID: 27,
    Category: "Sports",
    Subcategory: "Nutrition",
    Size: "Small",
    Color: "Yellow",
    Material: "Wood",
    Brand: "Gamma",
    "Price Range": "Budget",
    Rating: 3,
    "In Stock": false,
    "Shipping Weight": 14.61,
    "Age Group": "Seniors",
  },
  {
    ID: 28,
    Category: "Clothing",
    Subcategory: "Dresses",
    Size: "Medium",
    Color: "Purple",
    Material: "Leather",
    Brand: "Beta",
    "Price Range": "Budget",
    Rating: 4,
    "In Stock": true,
    "Shipping Weight": 14.07,
    "Age Group": "Seniors",
  },
  {
    ID: 29,
    Category: "Food",
    Subcategory: "Fresh",
    Size: "Small",
    Color: "Green",
    Material: "Leather",
    Brand: "Delta",
    "Price Range": "Luxury",
    Rating: 5,
    "In Stock": true,
    "Shipping Weight": 17.71,
    "Age Group": "Children",
  },
  {
    ID: 30,
    Category: "Home",
    Subcategory: "Bath",
    Size: "Small",
    Color: "Black",
    Material: "Cotton",
    Brand: "Beta",
    "Price Range": "Premium",
    Rating: 1,
    "In Stock": true,
    "Shipping Weight": 5.96,
    "Age Group": "Seniors",
  },
];

export function useDemoCrossfilter() {
  const ref = crossfilter(demoData);

  const dim1 = ref.dimension((d) => d.ID);
  const dim2 = ref.dimension((d) => d.ID);

  const dataHash = demoData.reduce((acc, d) => {
    acc[d.ID] = d;
    return acc;
  }, {} as Record<number, (typeof demoData)[number]>);

  const group1 = dim1.group().reduceCount();
  const group2 = dim2.group().reduceCount();

  // get counts as they sit
  const counts1 = group1.all();
  const counts2 = group2.all();

  console.log("all categories", cloneDeep(demoData.map((d) => d.Category)));

  console.log("counts1", cloneDeep(counts1));
  console.log("counts2", cloneDeep(counts2));

  // apply filtering
  dim1.filterFunction((c) => dataHash[c].Category === "Electronics");

  console.log("counts1After_post_filter", cloneDeep(group1.all()));
  console.log("counts2After_post_filter", cloneDeep(group2.all()));

  dim2.filterFunction((c) => dataHash[c].Category === "Sports");

  // get counts after filtering

  console.log("counts1After", cloneDeep(group1.all()));
  console.log("counts2After", cloneDeep(group2.all()));

  return {
    ref,
    dim1,
    dim2,
    dataHash,
  };
}
