export const basicNumbersSettings = {
  charts: [
    // {
    //   title: "Scatter Plot -  vs __ID",
    //   type: "scatter",
    //   field: "",
    //   layout: { x: 5, y: 0, w: 6, h: 4 },
    //   xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
    //   yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
    //   margin: { top: 20, right: 20, bottom: 20, left: 20 },
    //   facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
    //   xAxisLabel: "",
    //   yAxisLabel: "",
    //   xGridLines: 5,
    //   yGridLines: 5,
    //   xField: "ID",
    //   yField: "Square Root",
    //   xFilterRange: null,
    //   yFilterRange: null,
    //   id: "e0595e71-26a0-4464-bd5d-a1f8dc3f3dac",
    // },
    {
      title: "Data Summary",
      type: "summary",
      field: "",
      layout: { x: 0, y: 0, w: 5, h: 6 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      id: "9c8a9f83-916a-4beb-910a-902b58cfe5d8",
    },
    // {
    //   title: "Scatter Plot -  vs __ID",
    //   type: "scatter",
    //   field: "",
    //   layout: { x: 5, y: 4, w: 6, h: 4 },
    //   xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
    //   yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
    //   margin: { top: 20, right: 20, bottom: 20, left: 20 },
    //   facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
    //   xAxisLabel: "",
    //   yAxisLabel: "",
    //   xGridLines: 5,
    //   yGridLines: 5,
    //   xField: "ID",
    //   yField: "Squared",
    //   xFilterRange: null,
    //   yFilterRange: null,
    //   id: "d546814a-3134-4603-be3c-b576b9cec17d",
    // },
    // {
    //   title: "Scatter Plot -  vs __ID",
    //   type: "scatter",
    //   field: "",
    //   layout: { x: 0, y: 8, w: 12, h: 4 },
    //   xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
    //   yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
    //   margin: { top: 20, right: 20, bottom: 20, left: 20 },
    //   facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
    //   xAxisLabel: "",
    //   yAxisLabel: "",
    //   xGridLines: 5,
    //   yGridLines: 5,
    //   xField: "ID",
    //   yField: "Cosine",
    //   xFilterRange: null,
    //   yFilterRange: null,
    //   id: "f14ee0d1-0d3a-494d-abb9-31154832f45a",
    // },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: true,
  },
  metadata: {
    name: "Untitled",
    version: 1,
    createdAt: "2025-03-05T04:48:57.531Z",
    modifiedAt: "2025-03-05T04:48:57.531Z",
  },
  colorScales: [],
};
