import { SavedDataStructure } from "@/types/SavedDataTypes";

export const boxPlotSettings: SavedDataStructure = {
  charts: [
    {
      title: "Summary Table",
      type: "summary",
      field: "",
      layout: { x: 0, y: 0, w: 6, h: 5 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: {},
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "2d71ef50-9f8f-4435-8577-99d84a24e28e",
    },
    {
      title: "Box Plot",
      type: "boxplot",
      field: "Water Consumption (L)",
      layout: { x: 6, y: 4, w: 6, h: 4 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      colorScaleId: "0867bff2-86d3-48ff-9ef4-353575e0b156",
      colorField: "Mood Index",
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [{ type: "value", field: "Mood Index", values: [3] }],
      id: "ab0ba5ba-7bc5-486a-ae77-070dabfa2a39",
      whiskerType: "tukey",
      showOutliers: true,
      violinOverlay: true,
      beeSwarmOverlay: false,
      styles: {
        boxFill: "hsl(217.2 91.2% 59.8%)",
        boxStroke: "black",
        boxStrokeWidth: 1,
        medianStroke: "white",
        medianStrokeWidth: 2,
        whiskerStroke: "black",
        whiskerStrokeWidth: 1,
        outlierSize: 3,
        outlierStroke: "black",
        outlierFill: "none",
      },
    },
    {
      title: "Bar Chart",
      type: "bar",
      field: "Mood Index",
      layout: { x: 6, y: 0, w: 6, h: 4 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: {},
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "003dc550-7e3d-4eb4-8c8d-7dccd1b52c87",
      binCount: 10,
    },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: true,
  },
  metadata: {
    name: "Untitled",
    version: 1,
    createdAt: "2025-03-10T01:58:09.878Z",
    modifiedAt: "2025-03-10T01:58:09.878Z",
  },
  colorScales: [
    {
      name: "Mood Index",
      type: "numerical",
      palette: "Viridis",
      min: 1,
      max: 10,
      id: "0867bff2-86d3-48ff-9ef4-353575e0b156",
    },
  ],
};
