export const categoricalSmallSettings = {
  charts: [
    {
      title: "Data Summary",
      type: "summary",
      field: "",
      layout: { x: 0, y: 0, w: 6, h: 6 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      id: "a4a09ac0-43bb-4c46-bd25-5ca0b1fd6a56",
    },
    {
      title: "Data Table",
      type: "data-table",
      field: "",
      layout: { x: 6, y: 0, w: 6, h: 4 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      columns: [],
      visibleColumns: [],
      columnWidths: {},
      pageSize: 10,
      currentPage: 1,
      sortConfig: [],
      filters: {},
      groupBy: [],
      expandedGroups: {},
      selectedRows: {},
      id: "0ecad4f5-288f-48a3-8ae2-942d24780120",
    },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: true,
  },
  metadata: {
    name: "Untitled",
    version: 1,
    createdAt: "2025-03-06T02:52:05.189Z",
    modifiedAt: "2025-03-06T02:52:05.189Z",
  },
  colorScales: [],
};
