export const categoricalChartSettings = {
  charts: [
    {
      title: "Row Chart: ",
      type: "row",
      field: "Category",
      layout: { x: 7, y: 0, w: 5, h: 4 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      minRowHeight: 30,
      maxRowHeight: 50,
      filterValues: { values: [] },
      id: "2437c0f2-6ad0-4b1d-a47b-445ab15056b1",
    },
    {
      title: "Pivot Table",
      type: "pivot",
      field: "",
      layout: { x: 0, y: 0, w: 7, h: 5 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      rowFields: ["Category", "Subcategory"],
      columnFields: ["Rating"],
      valueFields: [{ field: "Category", aggregation: "count" }],
      showTotals: { row: false, column: false, grand: false },
      id: "7a345418-85b6-42d7-a86d-018cefe74d6e",
    },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: true,
  },
  metadata: {
    name: "Untitled",
    version: 1,
    createdAt: "2025-03-05T04:35:17.662Z",
    modifiedAt: "2025-03-05T04:35:17.662Z",
  },
  colorScales: [],
};
