import { SavedDataStructure } from "@/types/SavedDataTypes";

export const lineChartSettings: SavedDataStructure = {
  charts: [
    {
      title: "Data Summary",
      type: "summary",
      field: "",
      layout: { x: 0, y: 0, w: 5, h: 6 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      id: "9c8a9f83-916a-4beb-910a-902b58cfe5d8",
    },
    {
      id: "22b47715-2956-4f55-9274-224d3835eff4",
      type: "line",
      title: "",
      field: "",
      layout: { x: 5, y: 0, w: 6, h: 4 },
      facet: {
        enabled: false,
        type: "grid",
        rowVariable: "",
        columnCount: 2,
        columnVariable: "",
      },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      filters: [],
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      xField: "ID",
      seriesField: ["Value", "Squared", "Square Root", "Natural Log"],
      seriesSettings: {
        Value: {
          showPoints: false,
          pointSize: 4,
          pointOpacity: 1,
          lineWidth: 2,
          lineOpacity: 0.8,
          lineStyle: "solid",
          useRightAxis: false,
        },
        Squared: {
          showPoints: false,
          pointSize: 4,
          pointOpacity: 1,
          lineWidth: 2,
          lineOpacity: 0.8,
          lineStyle: "solid",
          useRightAxis: true,
        },
        "Square Root": {
          showPoints: false,
          pointSize: 4,
          pointOpacity: 1,
          lineWidth: 2,
          lineOpacity: 0.8,
          lineStyle: "solid",
          useRightAxis: false,
        },
        "Natural Log": {
          showPoints: false,
          pointSize: 4,
          pointOpacity: 1,
          lineWidth: 2,
          lineOpacity: 0.8,
          lineStyle: "solid",
          useRightAxis: false,
        },
      },
      styles: { curveType: "linear" },
      showXGrid: true,
      showYGrid: true,
      showLegend: true,
      legendPosition: "top",
    },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: true,
  },
  metadata: {
    name: "Untitled",
    version: 1,
    createdAt: "2025-03-11T02:29:25.186Z",
    modifiedAt: "2025-03-11T02:29:25.187Z",
  },
  colorScales: [],
};
