import { SavedDataStructure } from "@/types/SavedDataTypes";

export const demoSettings: SavedDataStructure = {
  charts: [
    {
      title: "2D View",
      type: "scatter",
      field: "Run ID",
      layout: { x: 0, y: 0, w: 3, h: 3 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      colorScaleId: "b9b0fa64-5d7b-4fdc-b191-daeb7920ecb3",
      colorField: "Run ID",
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      xField: "Time",
      yField: "Z",
      filters: [],
      id: "5cc180fb-d35e-4249-a46c-cba04f13b6a8",
    },
    {
      title: "Facet by run so each is its own chart",
      type: "3d-scatter",
      field: "Run ID",
      layout: { x: 3, y: 0, w: 9, h: 7 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: {
        enabled: true,
        type: "wrap",
        rowVariable: "Run ID",
        columnCount: 3,
      },
      colorScaleId: "b9b0fa64-5d7b-4fdc-b191-daeb7920ecb3",
      colorField: "Run ID",
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      xField: "X",
      yField: "Y",
      filters: [],
      id: "be9caf07-92eb-43ad-b3d5-4d3853c259c9",
      zField: "Z",
      cameraPosition: {
        x: -17.93186528327538,
        y: 10.101726965484353,
        z: -27.491089684368024,
      },
      cameraTarget: { x: 0, y: 0, z: 0 },
      pointSize: 1,
      pointOpacity: 0.8,
      showGrid: true,
      showAxes: true,
      zAxis: {
        scaleType: "linear",
        grid: false,
        min: 0,
        max: 100,
        zoomLevel: 1,
      },
    },
    {
      title: "All Runs together, use color",
      type: "3d-scatter",
      field: "Run ID",
      layout: { x: 0, y: 3, w: 3, h: 4 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: {
        enabled: false,
        type: "wrap",
        rowVariable: "Run ID",
        columnCount: 3,
      },
      colorScaleId: "b9b0fa64-5d7b-4fdc-b191-daeb7920ecb3",
      colorField: "Run ID",
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      xField: "X",
      yField: "Y",
      filters: [],
      zField: "Z",
      cameraPosition: {
        x: -4.331613307291414,
        y: 18.460295875011493,
        z: -18.640629992563348,
      },
      cameraTarget: { x: 0, y: 0, z: 0 },
      pointSize: 0.4,
      pointOpacity: 0.8,
      showGrid: true,
      showAxes: true,
      zAxis: {
        scaleType: "linear",
        grid: false,
        min: 0,
        max: 100,
        zoomLevel: 1,
      },
      id: "63671467-96ba-49f1-87a6-5310a20e1a60",
    },
    {
      title: "",
      type: "row",
      field: "Run ID",
      layout: { x: 5, y: 7, w: 6, h: 4 },
      xAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      yAxis: { scaleType: "linear", grid: false, min: 0, max: 100 },
      margin: { top: 20, right: 20, bottom: 20, left: 20 },
      facet: { enabled: false, type: "wrap", rowVariable: "", columnCount: 2 },
      xAxisLabel: "",
      yAxisLabel: "",
      xGridLines: 5,
      yGridLines: 5,
      filters: [],
      minRowHeight: 30,
      maxRowHeight: 50,
      id: "1991bcf0-f8e8-46a8-979d-812f01906c1f",
    },
  ],
  calculations: [],
  gridSettings: {
    columnCount: 12,
    rowHeight: 100,
    containerPadding: 10,
    showBackgroundMarkers: true,
  },
  metadata: {
    name: "Untitled",
    version: 1,
    createdAt: "2025-03-08T05:08:18.715Z",
    modifiedAt: "2025-03-08T05:08:18.715Z",
  },
  colorScales: [
    {
      name: "Run ID",
      type: "numerical",
      palette: "Viridis",
      min: 1,
      max: 5,
      id: "b9b0fa64-5d7b-4fdc-b191-daeb7920ecb3",
    },
    {
      name: "Time",
      type: "numerical",
      palette: "Viridis",
      min: 0,
      max: 1.99,
      id: "1b703a82-284c-4b1d-a32f-b6f2d3eb4049",
    },
  ],
};
